/* KEFE Visualiser — canonical typography system */
(() => {
  'use strict';
  const scale={ratio:1.25,micro:10,caption:12.5,label:15.625,body:19.53125,bodyLarge:24.414,title:30.518,display:38.147,displayXL:47.684};
  const families={ui:'Open Sans',apple:'Open Sans',brat:'Archivo Narrow',eternal:'Homemade Apple',aurora:'Bricolage Grotesque',typewriter:'Courier Prime',instagram:'Inter Tight',fadeup:'Momo Trust Display',kinetic:'Open Sans',liquid:'Bricolage Grotesque',lightfield:'Open Sans',morph:'Open Sans',mixedmedia:'Open Sans'};
  const effects={apple:{family:families.apple,weight:700,min:42,max:150,lineHeight:1.08,tracking:-.020,align:'center',case:'none',opticalScale:1},brat:{family:families.brat,weight:700,min:36,max:150,lineHeight:.94,tracking:-.055,align:'center',case:'none',opticalScale:1.04},eternal:{family:families.eternal,weight:400,min:34,max:150,lineHeight:1,tracking:.004,align:'left',case:'none',opticalScale:.98},aurora:{family:families.aurora,weight:500,min:38,max:150,lineHeight:1.05,tracking:-.006,align:'center',case:'none',opticalScale:1},typewriter:{family:families.typewriter,weight:400,min:32,max:140,lineHeight:1.02,tracking:.020,align:'center',case:'none',opticalScale:.98},instagram:{family:families.instagram,weight:800,min:48,max:150,lineHeight:.78,tracking:-.035,align:'center',case:'upper',opticalScale:1},fadeup:{family:families.fadeup,weight:400,min:34,max:150,lineHeight:1.08,tracking:-.006,align:'center',case:'none',opticalScale:.98},kinetic:{family:families.kinetic,weight:800,min:38,max:156,lineHeight:1,tracking:-.018,align:'center',case:'none',opticalScale:1},liquid:{family:families.liquid,weight:500,min:38,max:150,lineHeight:1,tracking:-.010,align:'center',case:'none',opticalScale:1},lightfield:{family:families.lightfield,weight:700,min:42,max:150,lineHeight:1,tracking:-.020,align:'center',case:'none',opticalScale:1},morph:{family:families.morph,weight:800,min:38,max:156,lineHeight:1,tracking:-.018,align:'center',case:'none',opticalScale:1},mixedmedia:{family:families.mixedmedia,weight:800,min:34,max:150,lineHeight:1,tracking:.012,align:'center',case:'none',opticalScale:1}};
  const fontFaces=['400 1em "Open Sans"','700 1em "Open Sans"','800 1em "Open Sans"','700 1em "Archivo Narrow"','400 1em "Homemade Apple"','400 1em "Courier Prime"','700 1em "Courier Prime"','800 1em "Inter Tight"','400 1em "Momo Trust Display"','500 1em "Bricolage Grotesque"'];
  const ready=(async()=>{if(!document.fonts?.ready)return true;const results=await Promise.all(fontFaces.map(face=>document.fonts.load(face).then(()=>true).catch(()=>false)));if(results.some(ok=>!ok))console.warn('KEFE: one or more effect fonts failed to load');return results.every(Boolean);})();
  window.KEFE_TYPE=Object.freeze({scale,families,effects,ready});window.kefeTypographyReady=ready;
  const redraw=()=>{try{window.redrawCurrentPreviewFrame?.();}catch(_){}};
  const premium=[['kinetic','Kinetic','Intelligent cinematic typography'],['liquid','Liquid','Fluid, morphing letterform motion'],['lightfield','Lightfield','Typography integrated with light and depth'],['morph','Morph','Continuous letterform transformation']];
  function install(){const section=document.getElementById('effectSection'),controls=document.getElementById('effectControls');if(!section||!controls)return;const buttons=section.querySelector('.effect-buttons');if(!buttons)return;premium.forEach(([name,label,description])=>{if(buttons.querySelector(`[data-effect="${name}"]`))return;const b=document.createElement('button');b.type='button';b.dataset.effect=name;b.textContent=label;b.title=description;buttons.appendChild(b);});const setActive=name=>{window.state.style.effect=name;buttons.querySelectorAll('[data-effect]').forEach(b=>b.classList.toggle('active-effect',b.dataset.effect===name));const label=document.getElementById('effectLabel');if(label)label.textContent=premium.find(x=>x[0]===name)?.[2]||label.textContent;redraw();};buttons.querySelectorAll('[data-effect]').forEach(b=>{if(b.dataset.kefePremiumBound==='1')return;b.dataset.kefePremiumBound='1';b.addEventListener('click',()=>setActive(b.dataset.effect));});if(!window.KEFE_PREMIUM_EFFECTS_LOADING){window.KEFE_PREMIUM_EFFECTS_LOADING=true;['kinetic','liquid','lightfield','morph'].forEach(name=>{const script=document.createElement('script');script.src=`./effects/${name}.js`;script.async=false;document.body.appendChild(script);});}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();ready.then(()=>window.dispatchEvent(new CustomEvent('kefe:fonts-ready')));
})();
