/* KEFE Visualiser — Fade Up + Rise / Slide / Drop / Drift lyric effects */
(() => {
  'use strict';
  const u = window.kefeEffectUtils;
  window.kefeEffects = window.kefeEffects || {};
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
  const smooth=v=>{const t=clamp(v);return t*t*(3-2*t);};
  const smoother=v=>{const t=clamp(v);return t*t*t*(t*(t*6-15)+10);};
  const BASE_FONTS=[
    {value:'Open Sans',label:'Open Sans',weight:700,group:'KEFE Fonts'},
    {value:'Archivo Narrow',label:'Archivo Narrow',weight:700,group:'KEFE Fonts'},
    {value:'Bricolage Grotesque',label:'Bricolage Grotesque',weight:700,group:'KEFE Fonts'},
    {value:'Courier Prime',label:'Courier Prime',weight:700,group:'KEFE Fonts'},
    {value:'Inter Tight',label:'Inter Tight',weight:700,group:'KEFE Fonts'},
    {value:'Momo Trust Display',label:'Momo Trust Display',weight:400,group:'KEFE Fonts'},
    {value:'Homemade Apple',label:'Homemade Apple',weight:400,group:'KEFE Fonts'},
    {value:'system-ui',label:'System UI — Default',weight:700,group:'System Fonts'},
    {value:'-apple-system',label:'Apple System',weight:700,group:'System Fonts'},
    {value:'BlinkMacSystemFont',label:'macOS System',weight:700,group:'System Fonts'},
    {value:'sans-serif',label:'Sans Serif',weight:700,group:'System Fonts'},
    {value:'serif',label:'Serif',weight:700,group:'System Fonts'},
    {value:'monospace',label:'Monospace',weight:700,group:'System Fonts'},
    {value:'cursive',label:'Cursive',weight:400,group:'System Fonts'},
    {value:'fantasy',label:'Fantasy',weight:700,group:'System Fonts'}
  ];
  const FONT_KEY='kefe-motion-font-v2';
  const getFont=name=>BASE_FONTS.find(f=>f.value===name)||BASE_FONTS[0];
  function setMotionFont(ctx,family,size){const f=getFont(family);ctx.font=`${f.weight} ${Math.max(18,size)}px "${f.value}", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif`;return f;}
  function trackedWidth(ctx,text,tracking){const chars=Array.from(String(text));if(!chars.length)return 0;return chars.reduce((s,c)=>s+ctx.measureText(c).width,0)+Math.max(0,chars.length-1)*tracking;}
  function fitMotionText(ctx,text,requested,tracking,maxWidth,family){let size=Math.max(30,Math.min(150,Number(requested)||76));setMotionFont(ctx,family,size);while(size>30&&trackedWidth(ctx,text,tracking*size)>maxWidth){size--;setMotionFont(ctx,family,size);}return{size,width:trackedWidth(ctx,text,tracking*size)};}
  function wrapWords(ctx,words,size,tracking,maxWidth,family){setMotionFont(ctx,family,size);const gap=Math.max(12,size*.16),rows=[];let row=[],width=0;for(const word of words){const wordWidth=trackedWidth(ctx,word.text,tracking),proposed=row.length?width+gap+wordWidth:wordWidth;if(row.length&&proposed>maxWidth){rows.push({words:row,width});row=[];width=0;}row.push({...word,width:wordWidth});width=row.length===1?wordWidth:width+gap+wordWidth;}if(row.length)rows.push({words:row,width});return rows;}
  function fit(ctx,words,requested,tracking,maxWidth,family){let size=Math.max(34,Math.min(150,Number(requested)||78));while(size>34){const rows=wrapWords(ctx,words,size,tracking*size,maxWidth,family);if(rows.length<=2)return{size,rows};size-=2;}return{size,rows:wrapWords(ctx,words,size,tracking*size,maxWidth,family)};}
  window.kefeEffects.fadeup=function(ctx,w,h,style,lines,time){const active=u.activeLine(lines,time);if(!active)return;const words=u.wordsFor(active.line,active.next);if(!words.length)return;const contract=u.contract('fadeup'),tracking=Number(contract.tracking)||0,family=getFont(style.kefeMotionFont).value,prepared=fit(ctx,words,style.fontSize,tracking,w*.80,family),size=prepared.size,rows=prepared.rows,trackingPx=tracking*size,rowHeight=size*1.12,top=h*.50-((rows.length-1)*rowHeight)/2,gap=Math.max(12,size*.16),colour=style.textColor||'#FFFFFF',accent=style.accentColor||colour;ctx.save();ctx.textAlign='left';ctx.textBaseline='middle';ctx.globalCompositeOperation='source-over';ctx.filter='none';setMotionFont(ctx,family,size);rows.forEach((row,rowIndex)=>{let x=(w-row.width)/2;const y=top+rowIndex*rowHeight;for(const word of row.words){const wp=u.wordProgress(word,time),p=clamp(wp.raw);if(p<=0){x+=word.width+gap;continue;}const enter=smoother(p/.28),settle=smoother((p-.18)/.42),rise=(1-enter)*size*.28,scale=.965+.035*settle,alpha=enter,glow=settle*size*.055;ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=colour;ctx.shadowColor=accent;ctx.shadowBlur=glow;ctx.translate(x+word.width/2,y+rise);ctx.scale(scale,scale);u.drawTrackedText(ctx,word.text,0,0,trackingPx,'fillText');ctx.restore();x+=word.width+gap;}});ctx.restore();};
  const MOTION={
    rise:{label:'Rise — soft upward lift with a clean cinematic settle',tracking:-.006,distance:.72,direction:'up',rotation:0,overshoot:.018,ghost:.06},
    slide:{label:'Slide — smooth lateral glide with a precise stop',tracking:-.006,distance:.76,direction:'left',rotation:0,overshoot:.012,ghost:.055},
    drop:{label:'Drop — controlled downward arrival with a subtle weighty settle',tracking:-.006,distance:.70,direction:'down',rotation:0,overshoot:.024,ghost:.045},
    drift:{label:'Drift — gentle diagonal float with barely-there rotation',tracking:-.006,distance:.66,direction:'diagonal',rotation:.020,overshoot:.010,ghost:.075}
  };
  function motionLine(ctx,w,h,style,active,time,mode){const line=String(active?.line?.text||'').trim();if(!line)return;const meta=MOTION[mode],family=getFont(style.kefeMotionFont).value,tracking=Number(meta?.tracking??-.006)||0,requested=Math.max(34,Math.min(150,Number(style.fontSize)||76)),prepared=fitMotionText(ctx,line,requested,tracking,w*.88,family),size=prepared.size,trackingPx=tracking*size,start=Number(active.line.time)||0,end=Math.max(start+.35,Number(active.line.endTime)||start+3),duration=end-start,enterDuration=Math.min(.46,Math.max(.20,duration*.19)),exitDuration=Math.min(.34,Math.max(.18,duration*.14)),enter=smoother((time-start)/enterDuration),exit=smoother((end-time)/exitDuration),opacity=enter*exit,settle=smoother((time-start-enterDuration*.48)/Math.max(.16,enterDuration*.68)),anticipation=1-smoother((time-start)/Math.max(.08,enterDuration*.22)),distance=Math.min(w*.20,size*meta.distance);let dx=0,dy=0,rotation=0;if(meta.direction==='up')dy=(1-enter)*distance-anticipation*size*.035;else if(meta.direction==='left')dx=(1-enter)*distance-anticipation*size*.035;else if(meta.direction==='down')dy=-(1-enter)*distance+anticipation*size*.035;else{dx=(1-enter)*distance*.72-anticipation*size*.025;dy=(1-enter)*distance*.28-anticipation*size*.018;rotation=(1-enter)*meta.rotation;}const settleWave=Math.sin(clamp((time-start)/Math.max(.01,enterDuration))*Math.PI)*(1-enter)*meta.overshoot*size;if(meta.direction==='up')dy-=settleWave;else if(meta.direction==='down')dy+=settleWave;else dx-=settleWave*(meta.direction==='left'?1:.55);const scale=.985+.015*settle,colour=style.textColor||'#FFFFFF',accent=style.accentColor||colour,glow=size*(.010+.014*settle);ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.globalCompositeOperation='source-over';ctx.filter='none';setMotionFont(ctx,family,size);if(meta.ghost>0&&enter<.92&&opacity>.01){ctx.save();ctx.globalAlpha=opacity*meta.ghost*(1-enter);ctx.fillStyle=accent;ctx.shadowColor=accent;ctx.shadowBlur=size*.035;ctx.translate(w/2+dx*.35,h*.76+dy*.35);ctx.rotate(rotation*.35);ctx.scale(scale,scale);u.drawTrackedText(ctx,line,0,0,trackingPx,'fillText');ctx.restore();}ctx.globalAlpha=opacity;ctx.fillStyle=colour;ctx.shadowColor=accent;ctx.shadowBlur=glow;ctx.translate(w/2+dx,h*.76+dy);ctx.rotate(rotation);ctx.scale(scale,scale);u.drawTrackedText(ctx,line,0,0,trackingPx,'fillText');ctx.restore();}
  for(const name of Object.keys(MOTION))window.kefeEffects[name]=(ctx,w,h,style,lines,time)=>{const active=u.activeLine(lines,time);if(active)motionLine(ctx,w,h,style,active,time,name);};
  function installMotionEffects(){if(window.__kefeMotionEffectsInstalled)return true;if(typeof window.render!=='function')return false;const originalRender=window.render,extra=new Set(Object.keys(MOTION));window.render=function(ctx,w,h,appState,mediaCache){const effect=appState?.style?.effect;if(!extra.has(effect))return originalRender(ctx,w,h,appState,mediaCache);const style=appState.style,lines=appState.captions?.mode==='captions'&&Array.isArray(appState.captions.lines)&&appState.captions.lines.length?appState.captions.lines:(Array.isArray(appState.lyrics?.lines)?appState.lyrics.lines:[]),time=Number(appState.playback?.currentTime)||0;const originalEffect=style.effect,originalText=style.textColor,originalAccent=style.accentColor,originalOpacity=style.appleInactiveOpacity;try{style.effect='apple';style.textColor='rgba(0,0,0,0)';style.accentColor='rgba(0,0,0,0)';style.appleInactiveOpacity=0;originalRender(ctx,w,h,appState,mediaCache);}finally{style.effect=originalEffect;style.textColor=originalText;style.accentColor=originalAccent;style.appleInactiveOpacity=originalOpacity;}if(lines.length)window.kefeEffects[effect](ctx,w,h,style,lines,time);};window.__kefeMotionEffectsInstalled=true;return true;}
  function addMotionButtons(){const host=document.querySelector('#lyricStyleBlock .effect-buttons');if(!host||host.querySelector('[data-effect="rise"]'))return;const fragment=document.createDocumentFragment();for(const[name,meta]of Object.entries(MOTION)){const button=document.createElement('button');button.type='button';button.className='segmented-btn';button.dataset.effect=name;button.textContent=name[0].toUpperCase()+name.slice(1);button.addEventListener('click',()=>{if(typeof window.setEffect==='function')window.setEffect(name);const label=document.getElementById('effectLabel');if(label)label.textContent=meta.label;document.querySelectorAll('[data-effect]').forEach(b=>b.classList.toggle('active-effect',b.dataset.effect===name));updateMotionFontVisibility();window.redrawCurrentPreviewFrame?.();});fragment.appendChild(button);}host.appendChild(fragment);addMotionFontControl();updateMotionFontVisibility();}
  function addMotionFontControl(){if(document.getElementById('kefeMotionFontControl'))return;const styleBlock=document.getElementById('lyricStyleBlock');if(!styleBlock)return;const row=document.createElement('label');row.id='kefeMotionFontControl';row.className='kefe-motion-font-control';row.textContent='Font';const select=document.createElement('select');select.id='kefeMotionFont';select.setAttribute('aria-label','Font for Rise, Slide, Drop and Drift');const groups={};for(const font of BASE_FONTS){const group=font.group||'Fonts';if(!groups[group]){groups[group]=document.createElement('optgroup');groups[group].label=group;select.appendChild(groups[group]);}const option=document.createElement('option');option.value=font.value;option.textContent=font.label;option.style.fontFamily=`"${font.value}",sans-serif`;groups[group].appendChild(option);}let saved=window.state?.style?.kefeMotionFont;try{saved=saved||localStorage.getItem(FONT_KEY);}catch(_){}select.value=BASE_FONTS.some(f=>f.value===saved)?saved:'Open Sans';if(window.state?.style)window.state.style.kefeMotionFont=select.value;select.addEventListener('change',()=>{if(window.state?.style)window.state.style.kefeMotionFont=select.value;try{localStorage.setItem(FONT_KEY,select.value);}catch(_){}window.redrawCurrentPreviewFrame?.();});row.appendChild(select);styleBlock.querySelector('.effect-buttons')?.insertAdjacentElement('afterend',row);}
  function updateMotionFontVisibility(){const control=document.getElementById('kefeMotionFontControl');if(!control)return;const selected=window.state?.style?.effect;control.style.display=Object.prototype.hasOwnProperty.call(MOTION,selected)?'grid':'none';}
  function initExtras(){installMotionEffects();addMotionButtons();updateMotionFontVisibility();if(!window.__kefeMotionEffectsInstalled||!document.querySelector('[data-effect="rise"]'))setTimeout(initExtras,50);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(initExtras,0),{once:true});else setTimeout(initExtras,0);
  const loadScrollLines=()=>{if(document.querySelector('script[data-kefe-scroll-lines]'))return;if(!document.head)return;const s=document.createElement('script');s.src='./effects/scroll-lines.js';s.dataset.kefeScrollLines='true';document.head.appendChild(s);};
  const loadUnifiedWizardEffects=()=>{if(document.querySelector('script[data-kefe-wizard-all-effects]'))return;if(!document.head)return;const s=document.createElement('script');s.src='./ui/wizard-all-effects.js';s.dataset.kefeWizardAllEffects='true';document.head.appendChild(s);};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{loadScrollLines();loadUnifiedWizardEffects();},{once:true});else{loadScrollLines();loadUnifiedWizardEffects();}
})();
