/* KEFE background presets. */
(() => {
'use strict';
const state=window.state,media=window.kefeMedia,grid=document.querySelector('.background-choice-grid');if(!state||!media||!grid)return;
const status=document.getElementById('backgroundStatus'),colorInput=document.getElementById('backgroundColor'),colorValue=document.getElementById('backgroundColorValue'),presets=[...grid.querySelectorAll('[data-background-preset]')];
const defs={gradient:{label:'Soft Gradient',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><linearGradient id="g"><stop stop-color="#241242"/><stop offset=".48" stop-color="#3a1f6b"/><stop offset="1" stop-color="#0b0518"/></linearGradient></defs><rect width="1080" height="1920" fill="url(#g)"/></svg>`},spotlight:{label:'Spotlight',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><radialGradient id="g" cx="50%" cy="40%" r="70%"><stop stop-color="#9a5a1e"/><stop offset=".45" stop-color="#2c1608"/><stop offset="1" stop-color="#080402"/></radialGradient></defs><rect width="1080" height="1920" fill="url(#g)"/></svg>`},aurora:{label:'Aurora Wash',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#04060d"/></svg>`},grid:{label:'Fine Grid',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#050a0d"/></svg>`},grain:{label:'Film Grain',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#160e06"/></svg>`}};
const clear=()=>{if(media.video){media.video.pause();media.video.src='';media.video=null}media.videoFile=null;media.videoHasAudio=false;media.image=null};
const select=k=>presets.forEach(x=>x.classList.toggle('active-background',x.dataset.backgroundPreset===k)),redraw=()=>window.redrawCurrentPreviewFrame?.();
const choose=key=>{if(window.isExporting)return;clear();if(key==='solid'){state.background.type='solid';select('solid');if(status)status.textContent=`Colour background · ${state.background.solid.toUpperCase()}`;redraw();return}const def=defs[key];if(!def)return;const img=new Image();img.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(def.svg)}`;img.onload=()=>{media.image=img;state.background.type='image';select(key);if(status)status.textContent=`${def.label} · ready`;redraw()}};
presets.forEach(x=>x.addEventListener('click',()=>choose(x.dataset.backgroundPreset)));colorInput?.addEventListener('input',()=>{clear();state.background.type='solid';state.background.solid=colorInput.value;if(colorValue)colorValue.textContent=colorInput.value.toUpperCase();select('solid');redraw()});select('solid');
})();
