/* KEFE background presets — clean, reusable canvas backgrounds. */
(() => {
  'use strict';
  const params=new URLSearchParams(document.currentScript?.src?.split('?')[1]||'');
  const runtime=params.get('runtime')==='1';
  if(!runtime){window.addEventListener('load',()=>{const thread=document.createElement('script');thread.src='./app/ui/web-threads.js?v=20260903-2';thread.async=false;document.body.appendChild(thread);const bridge=document.createElement('script');bridge.textContent='window.state = state;';document.body.appendChild(bridge);const script=document.createElement('script');script.src='./app/ui/background-presets.js?v=20260903-2&runtime=1';script.async=false;document.body.appendChild(script);},{once:true});return;}
  const state=window.state,media=window.kefeMedia,grid=document.querySelector('.background-choice-grid');if(!state||!media||!grid)return;
  const button=(()=>{let b=grid.querySelector('[data-background-preset="web-threads"]');if(b)return b;b=document.createElement('button');b.type='button';b.className='background-choice';b.dataset.backgroundPreset='web-threads';b.innerHTML='<span class="background-choice-preview"></span><span class="background-choice-label">Web Threads</span>';grid.appendChild(b);return b;})();
  const status=document.getElementById('backgroundStatus'),colorInput=document.getElementById('backgroundColor'),colorValue=document.getElementById('backgroundColorValue'),presets=[...grid.querySelectorAll('[data-background-preset]')];let threads=null;
  const defs={gradient:{label:'Soft Gradient',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><linearGradient id="g"><stop stop-color="#241242"/><stop offset=".48" stop-color="#3a1f6b"/><stop offset="1" stop-color="#0b0518"/></linearGradient></defs><rect width="1080" height="1920" fill="url(#g)"/></svg>`},spotlight:{label:'Spotlight',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><radialGradient id="g" cx="50%" cy="40%" r="70%"><stop stop-color="#9a5a1e"/><stop offset=".45" stop-color="#2c1608"/><stop offset="1" stop-color="#080402"/></radialGradient></defs><rect width="1080" height="1920" fill="url(#g)"/></svg>`},aurora:{label:'Aurora Wash',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><filter id="b"><feGaussianBlur stdDeviation="90"/></filter></defs><rect width="1080" height="1920" fill="#04060d"/><g filter="url(#b)" opacity=".88"><ellipse cx="200" cy="500" rx="340" ry="500" fill="#2f7bdc"/><ellipse cx="870" cy="800" rx="380" ry="540" fill="#c23fd0"/><ellipse cx="440" cy="1460" rx="440" ry="360" fill="#12d6a0"/></g></svg>`},grid:{label:'Fine Grid',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="1080" height="1920" fill="#050a0d"/><path d="M0 64h1080M64 0v1920" stroke="#38e0ff" stroke-opacity=".22"/></svg>`},grain:{label:'Film Grain',svg:`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><defs><radialGradient id="g"><stop stop-color="#4a331c"/><stop offset=".78" stop-color="#160e06"/></radialGradient></defs><rect width="1080" height="1920" fill="url(#g)"/></svg>`}};
  const clearMedia=()=>{if(threads){threads.stop();threads.destroy();threads=null;}if(media.video){media.video.pause();media.video.src='';media.video=null;}media.videoFile=null;media.videoHasAudio=false;media.image=null;};
  const select=k=>presets.forEach(b=>b.classList.toggle('active-background',b.dataset.backgroundPreset===k));const setStatus=t=>{if(status){status.textContent=t;status.className='status';}};const makeImage=svg=>{const img=new Image();img.decoding='async';img.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;return img;};
  const choosePreset=key=>{if(window.isExporting)return;clearMedia();if(key==='solid'){state.background.type='solid';select('solid');setStatus(`Colour background · ${state.background.solid.toUpperCase()}`);window.redrawCurrentPreviewFrame?.();return;}if(key==='web-threads'){if(!window.KefeWebThreads){setStatus('Web Threads is loading…');return;}threads=window.KefeWebThreads.create({...window.KefeWebThreads.defaults});media.image=threads.canvas;state.background.type='image';select(key);setStatus('Web Threads · live');window.redrawCurrentPreviewFrame?.();return;}const def=defs[key];if(!def)return;const img=makeImage(def.svg);img.onload=()=>{if(window.isExporting)return;media.image=img;state.background.type='image';select(key);setStatus(`${def.label} · ready`);window.redrawCurrentPreviewFrame?.();};};
  presets.forEach(b=>b.addEventListener('click',()=>choosePreset(b.dataset.backgroundPreset)));const solidTile=grid.querySelector('[data-background-preset="solid"]');const setSolidPreview=hex=>{if(solidTile)solidTile.style.setProperty('--kefe-bg-solid-preview',hex);};setSolidPreview(colorInput?.value||'#0A0A0A');colorInput?.addEventListener('input',()=>{if(window.isExporting)return;clearMedia();state.background.type='solid';state.background.solid=colorInput.value;if(colorValue)colorValue.textContent=colorInput.value.toUpperCase();setSolidPreview(colorInput.value);select('solid');setStatus(`Colour background · ${colorInput.value.toUpperCase()}`);window.redrawCurrentPreviewFrame?.();});select('solid');
  if(!document.querySelector('.kefe-web-threads-landing')&&window.KefeWebThreads){const landing=window.KefeWebThreads.create({...window.KefeWebThreads.defaults});landing.canvas.classList.add('kefe-web-threads-landing');document.body.prepend(landing.canvas);const glass=document.createElement('div');glass.className='kefe-web-threads-glass';document.body.insertBefore(glass,document.body.children[1]||null);document.body.classList.add('kefe-web-threads-landing-active');window.kefeLandingThreads=landing;}
})();
