/* KEFE Premium — MORPH
 * Letterform continuity system: phrases deform, stretch and resolve into the next phrase.
 */
(() => {
  'use strict';
  const u=window.kefeEffectUtils; window.kefeEffects=window.kefeEffects||{};
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,Number(v)||0));
  const smooth=v=>{const t=clamp(v);return t*t*(3-2*t);};
  const smoother=v=>{const t=clamp(v);return t*t*t*(t*(t*6-15)+10);};
  const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return(h>>>0)/4294967295;};
  const chars=text=>Array.from(String(text||''));
  function points(ctx,text,size){u.setContractFont(ctx,'kinetic',size);const c=chars(text);const widths=c.map(ch=>ctx.measureText(ch).width);const total=widths.reduce((a,b)=>a+b,0);let x=-total/2;return c.map((char,i)=>{const width=widths[i],p={char,x:x+width/2,width};x+=width;return p;});}
  function drawPhrase(ctx,text,size,maxWidth,x,y,alpha,phase,style,seed){if(!text)return;const pts=points(ctx,text,size);const total=pts.reduce((n,p)=>n+p.width,0);const fit=Math.min(1,maxWidth/Math.max(1,total));const intensity=clamp(style.morphIntensity??.82),wave=clamp(style.morphWave??.52),glow=clamp(style.morphGlow??.14);ctx.save();ctx.translate(x,y);ctx.scale(fit,fit);ctx.textAlign='center';ctx.textBaseline='middle';for(let i=0;i<pts.length;i++){const p=pts[i],n=hash(seed+':'+i),center=i/Math.max(1,pts.length-1)-.5;const w=Math.sin(phase*Math.PI*2+center*5+n*3)*size*.055*wave*intensity;const squeeze=1+Math.sin(phase*Math.PI+n*2.7)*.18*intensity;ctx.save();ctx.globalAlpha=alpha;ctx.translate(p.x,w);ctx.scale(squeeze,1/squeeze);ctx.fillStyle=style.textColor||'#fff';ctx.fillText(p.char,0,0);if(glow){ctx.globalAlpha=alpha*.12;ctx.shadowColor=style.accentColor||'#fff';ctx.shadowBlur=glow*size;ctx.fillText(p.char,0,0);}ctx.restore();}ctx.restore();}
  window.kefeEffects.morph=function(ctx,w,h,style,lines,time){const a=u.activeLine(lines,time);if(!a)return;const current=String(a.line.text||'').trim();if(!current)return;const next=String(a.next?.text||'').trim();const lp=u.lineProgress(a.line,time,.10,.22);const maxWidth=w*.82;const base=Number(style.fontSize)||86;const currentSize=u.fitContractText(ctx,'kinetic',current,base,maxWidth);const nextSize=next?u.fitContractText(ctx,'kinetic',next,base*.96,maxWidth):currentSize;const nextTime=Number(a.next?.time);const transition=Math.max(.18,Math.min(.5,(nextTime-(Number(a.line.time)||0))*.3||.3));const t=Number.isFinite(nextTime)?clamp((time-(nextTime-transition))/transition):0;const inP=smoother(t),outP=smoother(clamp(t/.78));const phase=clamp(lp.hold)+Math.sin(Math.PI*clamp(lp.hold))*.22;ctx.save();if(next&&t>0){const d=w*.035*clamp(style.morphIntensity??.82)*(1-inP);drawPhrase(ctx,current,currentSize,maxWidth,w/2-d*inP,h*.5,.96-.82*outP,phase,style,current+'|out');drawPhrase(ctx,next,nextSize,maxWidth,w/2+d*(1-inP),h*.5,.08+.92*inP,phase+.5,style,next+'|in');ctx.save();ctx.globalAlpha=.05*inP;ctx.filter=`blur(${Math.max(.5,currentSize*.025)}px)`;drawPhrase(ctx,current,currentSize,maxWidth,w/2,h*.5,1,phase+.2,style,current+'|bridge');ctx.restore();}else{const pulse=1+Math.sin(Math.PI*clamp(lp.hold))*.022*clamp(style.morphIntensity??.82);ctx.translate(w/2,h*.5);ctx.scale(pulse,pulse);drawPhrase(ctx,current,currentSize,maxWidth,0,0,lp.opacity,phase,style,current+'|stable');}ctx.restore();};
})();
